#!/usr/bin/env python3
"""
Create a two-dimensional (m_X, m_Y) figure from the exact XYH signal
process definitions used by the analysis.

Run this script from a configured XYH environment, for example:

    python plot_xyh_mass_grid.py --output-dir figures

It writes:
    figures/xyh_signal_mass_grid.pdf
    figures/xyh_signal_mass_grid.png
    figures/xyh_signal_mass_grid.csv
    figures/xyh_signal_mass_grid_info.tex
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np


PROCESS_PATTERN = re.compile(r"xyh_sl_x(?P<mass_x>\d+)_y(?P<mass_y>\d+)")
BENCHMARKS = (
    (600, 400, "Lower-edge benchmark"),
    (1000, 700, "Intermediate benchmark"),
    (2000, 1800, "Upper-edge benchmark"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the exact two-dimensional XYH signal mass grid.",
    )
    parser.add_argument(
        "--output-dir",
        default="figures",
        help="Directory in which the PDF, PNG, and CSV files are written.",
    )
    parser.add_argument(
        "--process-file",
        default=None,
        help=(
            "Optional path to a Python/text file containing process names such as "
            "'xyh_sl_x1000_y700'. When omitted, XYH_SIGNAL_PROCESSES is imported "
            "from xyh.inference.signals."
        ),
    )
    parser.add_argument(
        "--higgs-mass",
        type=float,
        default=125.0,
        help="SM-like Higgs-boson mass in GeV used for the threshold line.",
    )
    parser.add_argument(
        "--top-mass",
        type=float,
        default=172.5,
        help="Top-quark mass in GeV used for the Y -> ttbar threshold line.",
    )
    return parser.parse_args()


def load_process_names(process_file: str | None) -> tuple[str, ...]:
    if process_file:
        text = Path(process_file).expanduser().read_text(encoding="utf-8")
        return tuple(sorted(set(match.group(0) for match in PROCESS_PATTERN.finditer(text))))

    try:
        from xyh.inference.signals import XYH_SIGNAL_PROCESSES
    except Exception as exc:
        raise RuntimeError(
            "Could not import XYH_SIGNAL_PROCESSES. Run the script after sourcing "
            "the XYH analysis environment, or pass --process-file with the path "
            "to the CMSDB XYH process-definition file."
        ) from exc

    return tuple(str(name) for name in XYH_SIGNAL_PROCESSES)


def extract_mass_points(process_names: Iterable[str]) -> tuple[tuple[int, int], ...]:
    points: set[tuple[int, int]] = set()

    for process_name in process_names:
        match = PROCESS_PATTERN.fullmatch(process_name)
        if match is None:
            continue
        points.add(
            (
                int(match.group("mass_x")),
                int(match.group("mass_y")),
            )
        )

    if not points:
        raise RuntimeError("No process names matching 'xyh_sl_x<mX>_y<mY>' were found.")

    return tuple(sorted(points))


def validate_points(points: tuple[tuple[int, int], ...], higgs_mass: float) -> None:
    invalid = [(mx, my) for mx, my in points if mx <= my + higgs_mass]
    if invalid:
        formatted = ", ".join(f"({mx}, {my})" for mx, my in invalid)
        raise RuntimeError(
            "Found signal hypotheses that do not satisfy m_X > m_Y + m_H: "
            f"{formatted}"
        )

    missing_benchmarks = [
        (mx, my)
        for mx, my, _ in BENCHMARKS
        if (mx, my) not in points
    ]
    if missing_benchmarks:
        formatted = ", ".join(f"({mx}, {my})" for mx, my in missing_benchmarks)
        raise RuntimeError(
            "The following requested benchmark points are absent from the signal "
            f"definition: {formatted}"
        )


def write_csv(points: tuple[tuple[int, int], ...], output_path: Path) -> None:
    with output_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(["mass_x_GeV", "mass_y_GeV"])
        writer.writerows(points)


def write_latex_metadata(
    points: tuple[tuple[int, int], ...],
    output_path: Path,
) -> None:
    mass_x = [point[0] for point in points]
    mass_y = [point[1] for point in points]

    content = (
        "% Automatically generated by plot_xyh_mass_grid.py\n"
        f"\\newcommand{{\\NXYHSignalHypotheses}}{{{len(points)}}}\n"
        f"\\newcommand{{\\XYHMinMX}}{{{min(mass_x)}}}\n"
        f"\\newcommand{{\\XYHMaxMX}}{{{max(mass_x)}}}\n"
        f"\\newcommand{{\\XYHMinMY}}{{{min(mass_y)}}}\n"
        f"\\newcommand{{\\XYHMaxMY}}{{{max(mass_y)}}}\n"
    )
    output_path.write_text(content, encoding="utf-8")


def make_plot(
    points: tuple[tuple[int, int], ...],
    output_dir: Path,
    higgs_mass: float,
    top_mass: float,
) -> None:
    mass_x = np.asarray([point[0] for point in points], dtype=float)
    mass_y = np.asarray([point[1] for point in points], dtype=float)

    x_margin = 100.0
    y_margin = 100.0
    x_min = max(0.0, mass_x.min() - x_margin)
    x_max = mass_x.max() + x_margin
    y_min = max(0.0, min(mass_y.min(), 2.0 * top_mass) - y_margin)
    y_max = mass_y.max() + y_margin

    fig, ax = plt.subplots(figsize=(7.4, 6.3))

    ax.scatter(
        mass_x,
        mass_y,
        s=42,
        label=f"Generated signal hypotheses ({len(points)})",
        zorder=3,
    )

    benchmark_markers = ("*", "s", "D")
    benchmark_sizes = (180, 85, 85)

    for (mx, my, label), marker, size in zip(
        BENCHMARKS,
        benchmark_markers,
        benchmark_sizes,
    ):
        ax.scatter(
            [mx],
            [my],
            marker=marker,
            s=size,
            label=f"{label}: ({mx}, {my})",
            zorder=5,
        )
        ax.annotate(
            f"({mx}, {my})",
            xy=(mx, my),
            xytext=(7, 7),
            textcoords="offset points",
            fontsize=9,
        )

    x_values = np.linspace(x_min, x_max, 500)
    threshold_y = x_values - higgs_mass

    ax.plot(
        x_values,
        threshold_y,
        linestyle="--",
        linewidth=1.4,
        label=r"$m_X=m_Y+m_H$",
        zorder=2,
    )
    ax.fill_between(
        x_values,
        threshold_y,
        y_max,
        alpha=0.10,
        label=r"Kinematically forbidden for on-shell $X\to YH$",
        zorder=1,
    )

    ttbar_threshold = 2.0 * top_mass
    ax.axhline(
        ttbar_threshold,
        linestyle=":",
        linewidth=1.4,
        label=r"$m_Y=2m_t$",
        zorder=2,
    )

    ax.set_xlabel(r"$m_X$ [GeV]")
    ax.set_ylabel(r"$m_Y$ [GeV]")
    ax.set_title(r"Signal mass hypotheses for $X\to YH$, $Y\to t\bar{t}$, $H\to b\bar{b}$")

    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    ax.xaxis.set_major_locator(MultipleLocator(200))
    ax.xaxis.set_minor_locator(MultipleLocator(100))
    ax.yaxis.set_major_locator(MultipleLocator(200))
    ax.yaxis.set_minor_locator(MultipleLocator(100))
    ax.grid(True, which="major", alpha=0.30)
    ax.grid(True, which="minor", alpha=0.12)

    ax.legend(fontsize=8.5, loc="best")
    fig.tight_layout()

    pdf_path = output_dir / "xyh_signal_mass_grid.pdf"
    png_path = output_dir / "xyh_signal_mass_grid.png"
    csv_path = output_dir / "xyh_signal_mass_grid.csv"
    tex_path = output_dir / "xyh_signal_mass_grid_info.tex"

    fig.savefig(pdf_path, bbox_inches="tight")
    fig.savefig(png_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    write_csv(points, csv_path)
    write_latex_metadata(points, tex_path)

    print(f"Number of signal hypotheses: {len(points)}")
    print(f"m_X range: {int(mass_x.min())}--{int(mass_x.max())} GeV")
    print(f"m_Y range: {int(mass_y.min())}--{int(mass_y.max())} GeV")
    print(f"Wrote: {pdf_path}")
    print(f"Wrote: {png_path}")
    print(f"Wrote: {csv_path}")
    print(f"Wrote: {tex_path}")


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    process_names = load_process_names(args.process_file)
    points = extract_mass_points(process_names)
    validate_points(points, args.higgs_mass)
    make_plot(points, output_dir, args.higgs_mass, args.top_mass)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())